# Numpy Theoritical Questions and Answers

In [16]:
# Importing numpy once instead of importing every time and trying to keep programs clean and understable.
import numpy as np

### Question 1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
You can create a 3x3 NumPy array with random integers between 1 and 100 using the `numpy.random.randint()` function. To interchange (or swap) the rows and columns, you can use the `numpy.transpose()` function or simply use the `.T` attribute. Here's how to do it step by step:

In [17]:
# Create a 3x3 Numpy array with random integers between 1 and 100.
array_3x3 = np.random.randint(1 , 100, size=(3,3))
print("The Originial array is given below: \n", array_3x3)

#Now we Use numpy.transpose() or .T to interchange its rows and column.
transpose_array_3x3 = array_3x3.T
print("Interchange of the orignal 3x3 array is given below: \n",transpose_array_3x3)

The Originial array is given below: 
 [[ 3 38 73]
 [49 17 87]
 [69 49  6]]
Interchange of the orignal 3x3 array is given below: 
 [[ 3 49 69]
 [38 17 49]
 [73 87  6]]


This demonstrates how to create a 3x3 NumPy array with random integers and interchange its rows and columns.

## 2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [18]:
# Creating a 1D Numpy array with 10 elements
# Numpy already imported as np.
array_1d = np.array([1,2,3,4,5,6,7,8,9,10])
array_2x5 = array_1d.reshape(2,5)
array_5x2 = array_1d.reshape(5,2)
print("1D Array is given below: \n", array_1d)
print("2x5 Array of 1D Array is given below: \n", array_2x5)
print("5x2 Array of 1D Array is given below: \n", array_5x2)

1D Array is given below: 
 [ 1  2  3  4  5  6  7  8  9 10]
2x5 Array of 1D Array is given below: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5x2 Array of 1D Array is given below: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


## 3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

We can create a 4x4 NumPy array with random float values and then add a border of zeros around it to get a 6x6 array using the following code:

In [19]:
# Creating a 4x4 Numpy with random float values.
# Numpy already imported as np
array_4x4 = np.random.rand(4,4)

# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:")
print(array_4x4)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.91247654 0.89891947 0.05861165 0.96235135]
 [0.11359841 0.63928396 0.98496889 0.0413356 ]
 [0.70838017 0.88364023 0.9906876  0.78206073]
 [0.08704564 0.55551567 0.3041552  0.62949203]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.91247654 0.89891947 0.05861165 0.96235135 0.        ]
 [0.         0.11359841 0.63928396 0.98496889 0.0413356  0.        ]
 [0.         0.70838017 0.88364023 0.9906876  0.78206073 0.        ]
 [0.         0.08704564 0.55551567 0.3041552  0.62949203 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


This code generates a 4x4 array with random float values and then pads it with zeros to create a 6x6 array. The `np.pad` function is used for adding the border.

## 4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

You can create an array of integers from 10 to 60 with a step of 5 using NumPy's `arange` function. Here's how you can do it:

In [20]:
# import numpy as np (Already imported)

# Create the array
array = np.arange(10, 65, 5)  # 65 is used as the stop value (exclusive)

print(array)

[10 15 20 25 30 35 40 45 50 55 60]


## 5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

We can create a NumPy array of strings and then apply various case transformations to each element using NumPy's vectorized operations. Here's how you can do it:

In [21]:
# import numpy as np (Already imorted)

# Create the array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)
capitalize = np.char.capitalize(arr)

# Print the results
print("Original Array:", arr)
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", titlecase)
print("Capitalize:", capitalize)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


## 6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

We can generate a NumPy array of words and then insert a space between each character of every word using NumPy's vectorized string operations. Here's how to do it:

In [22]:
# import numpy as np (Already imported)

# Create the array of words
words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Print the result
print(spaced_words)


['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


## 7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

We can create two 2D NumPy arrays and then perform element-wise operations such as addition, subtraction, multiplication, and division. Here’s how you can do it:

In [23]:
# import numpy as np (Already Imported)

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Print the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## 8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

We can create a 5x5 identity matrix using NumPy's eye function and then extract its diagonal elements using the diag function. Here’s how to do it:

In [24]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


## 9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [25]:
# import numpy as np (Already Imported)

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Print the results
print("Random Integers:\n", random_integers)
print("Prime Numbers:", prime_numbers)


Random Integers:
 [774 843 549 883 315 704  56 976 439 199 295 742 482 207  66 176 383 419
 489 454 295 970 210 674 576 916 949 766 637 494  99 854 852 268 900 636
 820 211 567 325 693 729 654 134 582 327 304 218 712 116 906  52 207  46
 981 205 338 949 351 664 539 483 899 459 167  40  45 313 873 221 812 929
  86  58 461 752 904 758 746 144 675 935 151 828 351 750 441 361 599 770
 102 914 215 975 335 400 862 784 858 486]
Prime Numbers: [np.int32(883), np.int32(439), np.int32(199), np.int32(383), np.int32(419), np.int32(211), np.int32(167), np.int32(313), np.int32(929), np.int32(461), np.int32(151), np.int32(599)]


## 10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

We can create a NumPy array representing daily temperatures for a month (30 days) and then calculate the weekly averages. Here's how you can do it:

In [26]:
# import numpy as np (Already Imported)

# Generate a NumPy array representing daily temperatures for a month (30 days)
# Random temperatures between 0 and 35 degrees Celsius
daily_temperatures = np.random.randint(0, 36, size=30)

# Reshape the array to have 5 weeks (rows) and 6 days (columns)
weekly_temperatures = daily_temperatures.reshape(5, 6)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the results
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("Weekly Temperatures (5 weeks, 6 days each):\n", weekly_temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures for the Month:
 [13 17  7 13 20 18 28 23  5  8 35 24 33  2 11 13 16 30 34 26 19 32 10 21
  7 14 17 22 30 32]
Weekly Temperatures (5 weeks, 6 days each):
 [[13 17  7 13 20 18]
 [28 23  5  8 35 24]
 [33  2 11 13 16 30]
 [34 26 19 32 10 21]
 [ 7 14 17 22 30 32]]
Weekly Averages: [14.66666667 20.5        17.5        23.66666667 20.33333333]
